### ISSUE TITLE
Chrome view err for header & footer bar not found

### ISSUE THREAD

**Issue by kevin-kunihisa124** [jgraph/www.diagrams.net-source#116]
Chrome browser is not found for header & footer bar

Edge Browser is Correct
![view1](https://user-images.githubusercontent.com/113880535/190958007-c060e426-4383-4001-a975-93f5d8ca4ad5.png)

Chrome Browser is not correct view
![view2](https://user-images.githubusercontent.com/113880535/190958018-78c4ed86-72f4-4638-8eb3-69abcd4a5474.png)

Does anyone know of a solution?

**Comment by davidjgraph** [comment]
This is not the drawio repo.

**Comment by kevin-kunihisa124** [comment]
No, this is a DRAW.io report.
Could you please double check the screen capture?
Please also check the URL of the capture.

**Comment by davidjgraph** [comment]
And this still isn't the draw.io repo.
