### ISSUE TITLE
Gitflow diagram image is 404

### ISSUE THREAD

**Issue by SSteve** [jgraph/www.diagrams.net-source#176]
Clicking the gitflow diagram image (https://www.drawio.com/viewer.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fjgraph%2Fdrawio-diagrams%2Fdev%2Fblog%2Fgitflow-examples.drawio) at https://www.drawio.com/example-diagrams goes to Page Not Found.

**Comment by alderg** [comment]
Where did you get this link? The correct link should be https://viewer.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fjgraph%2Fdrawio-diagrams%2Fdev%2Fblog%2Fgitflow-examples.drawio

**Comment by SSteve** [comment]
https://www.drawio.com/example-diagrams

**Comment by SSteve** [comment]
I found a way to look at page source on the iPad. The link in the source looks correct. I don't know why the iPad is going to a different URL. I'll try power cycling and see what happens.
