### ISSUE TITLE
404s in blog: mindmaps-from-text, Atlassian, layers

### ISSUE THREAD

**Issue by definiteIymaybe** [jgraph/www.diagrams.net-source#196]
Hello,

I've come across some broken links on drawio.com:

1. **mindmaps-from-text**
   - **Broken Link:** [/blog/mindmaps-from-text.html](https://www.drawio.com/blog/mindmaps-from-text.html)  
   - **Found in:** [/blog/plantuml](https://www.drawio.com/blog/plantuml)  
   - **Probable Correct Link:** [/blog/plantuml-mindmaps-from-text](https://www.drawio.com/blog/plantuml-mindmaps-from-text)

2. **Atlassian**
   - **Broken Link:** [/blog/Atlassian.html](https://www.drawio.com/blog/Atlassian.html)  
   - **Found in:** [/blog](https://www.drawio.com/blog) (list of categories)  
   - **Probable Correct Link:** [/blog/atlassian](https://www.drawio.com/blog/atlassian)  
   - **Note:** There are two `Atlassian` categories on the blog page. The issue might be due to the capitalization in `Atlassian.html`. The link `/blog/atlassian.html` does redirect to `/blog/atlassian`.

3. **layers**
   - **Broken Link:** [/blog/layers.html](https://www.drawio.com/blog/layers.html)  
   - **Found in:** [/blog](https://www.drawio.com/blog) page (list of categories) and `layers` category link in the preview card of [blog/watermark-diagrams](https://www.drawio.com/blog/watermark-diagrams)
   - **Note:** Was unable to find a probable correct link / other posts that would belong to the `layers` category.

 Thank you for your work.

**Comment by davidjgraph** [comment]
These are fixed, thanks for the pointers.
