### ISSUE TITLE
Broken voice.js "how to use" link on plugins page

### ISSUE THREAD

**Issue by designosis** [jgraph/www.diagrams.net-source#237]
**Where**: https://www.drawio.com/doc/faq/plugins

**What**: The voice.js "(How to use)" link

**What happens**: I'm sent to https://www.drawio.com/doc/faq/voice-plugin.html, which shows ...
<img width="571" alt="Screenshot 2024-09-20 at 12 54 27 PM" src="https://github.com/user-attachments/assets/f139ebb0-4225-48f5-8f9b-485df63b81ad">

**What I expected**: Instructions on how to use the voice.js plugin

**Comment by kym-drawio** [comment]
Removed inactive plugins in PR 238.
