### ISSUE TITLE
Azure Site Diagram page dead links

### ISSUE THREAD

**Issue by radicaldo** [jgraph/www.diagrams.net-source#245]
At the bottom of this page:
https://www.drawio.com/blog/azure-diagrams

Under " Embed diagrams in the following documentation platforms"
The "Confluence Cloud" Link is dead: 

https://www.drawio.com/doc/faq/embed-copy-move-diagrams-confluence-cloud.html

![image](https://github.com/user-attachments/assets/c27597ab-702e-477a-aefe-bd9ba02f5408)

**Comment by kym-drawio** [comment]
Fixed in PR 247
