### ISSUE TITLE
Does diagrams.net have a gallery?

### ISSUE THREAD

**Issue by bbkane** [jgraph/www.diagrams.net-source#31]
Hello - I'd like to show off diagrams.net to some colleagues. Is there a gallery anywhere of nice diagrams made with the tool?

**Comment by davidjgraph** [comment]
No. We'd have to ask users to send diagrams in and then we're storing user data and have to change the privacy policy....

**Comment by bbkane** [comment]
I'm not a lawyer, but if you wrote a blog post asking users to send in diagrams for the purpose of a gallery, would that still be user data? Seems like it'd be a transfer of ownership.

The docs and blogs do have a good amount of pictures. It might be worth just collecting the existing diagrams onto one page. 

Anyway,  seems like you've thought about it. I'll go ahead and close the issue and maybe I'll make a personal blog post wirh some diagrams. Thank you for the tool!!
