### ISSUE TITLE
The Donate page is now 404

### ISSUE THREAD

**Issue by RoneoOrg** [jgraph/www.diagrams.net-source#64]
Hello there,
[I've been promoting](https://roneo.org/en/diagrams.net-adding-icons-font-awesome-twemoji#going-further) the Donate page, but the link is now broken, is it on purpose?
Cheers

**Comment by davidjgraph** [comment]
Thanks for the link. Not entirely sure what happened there, but https://github.com/sponsors/jgraph is good.

**Comment by RoneoOrg** [comment]
Link fixed, thanks!
