### ISSUE TITLE
Non-TLS download links

### ISSUE THREAD

**Issue by TomyLobo** [jgraph/www.diagrams.net-source#92]
See this search:
https://github.com/jgraph/www.diagrams.net-source/search?q=http%3A%2F%2Fget.diagrams.net
You should use https for all of those download links, so they cannot be MITM'ed.

Since the GitHub search is notoriously bad, don't rely on it for completeness.
Use `git grep 'http:'` instead.
The full repo is like a GB in size and I'm not going to download that over this line. I assume the people at JGraph have it checked out anyway :)

**Comment by TomyLobo** [comment]
The following command can be used to change _all_ http links to https:
```bash
git grep -lz 'http:' | xargs -0 sed -ri 's/http:/https:/g'
```
I'd still verify the result if I were you, though :)

**Comment by davidjgraph** [comment]
Thanks, fixed in https://github.com/jgraph/www.diagrams.net-source/commit/ca2b66950477b99b20ac2f5ad0c66aead2662728
